[package]
authors = ["Fabien Bellanger <valentil@gmail.com>"]
description = "Axum boilerplate"
edition = "2021"
name = "axum_boilerplate"
readme = "README.md"
repository = "https://github.com/fabienbellanger/axium-boilerplate"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[[bin]]
name = "api"
path = "src/bin/api.rs"

[dependencies]
anyhow = "1.0"
axum = "0.3"
bytes = "1.0"
chrono = {version = "0.4", features = ["serde"]}
color-eyre = "0.5"
config = "0.11"
derive_more = "0.99"
dotenv = "0.15"
env_logger = "0.9"
eyre = "0.6"
futures = "0.3"
log = "0.4"
reqwest = "0.11"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
tokio = {version = "1.12", features = ["full"]}
tower = "0.4"
tower-http = {version = "0.1", features = ["trace"]}
tracing = "0.1"
tracing-subscriber = "0.3"
uuid = {version = "0.8", features = ["serde", "v4"]}
