[package]
authors = ["Fabien Bellanger <valentil@gmail.com>"]
description = "Axum boilerplate"
edition = "2021"
name = "axum_boilerplate"
readme = "README.md"
repository = "https://github.com/fabienbellanger/axum-boilerplate"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[[bin]]
name = "axum-boilerplate-bin"
path = "src/bin/main.rs"

[features]
ws = []

[dependencies]

# Axum
axum = { version = "0.5.16", features = ["headers", "ws"] }

# Tower
tower = { version = "0.4.13", features = ["timeout"] }
tower-http = { version = "0.3.4", features = ["cors", "fs", "request-id"] }

# Log
env_logger = "0.9.0"
log = "0.4.17"
tracing = "0.1.36"
tracing-appender = "0.2.2"
tracing-subscriber = { version = "0.3.15", features = ["registry", "env-filter", "fmt", "json"] }

# Error
color-eyre = "0.6.2"
eyre = "0.6.8"
thiserror = "1.0.34"

# sqlx
sqlx = { version = "0.6.1", features = ["runtime-tokio-native-tls", "chrono", "mysql", "macros", "bigdecimal", "migrate", "offline"] }

# Redis
r2d2 = "0.8.10"
redis = { version = "0.21.6", features = ["r2d2"] }

# Tera
tera = "1.17.0"

async-stream = "0.3.3"
bytes = "1.2.1"
chrono = { version = "0.4.22", features = ["serde"] }
clap = { version = "3.2.20", features = ["derive"] }
config = "0.13.2"
derive_more = "0.99.17"
dotenv = "0.15.0"
futures = "0.3.24"
jsonwebtoken = "8.1.1"
lazy_static = "1.4.0"
lettre = "0.10.1"
mailchecker = "5.0.1"
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
sha2 = "0.10.5"
tokio = { version = "1.21.0", features = ["full"] }
uuid = { version = "1.1.2", features = ["serde", "v4"] }
validator = { version = "0.16.0", features = ["derive"] }
mime = "0.3.16"
rand = "0.8.5"
