name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Copy .env
      run: cp .env.example .env
    - name: Build
      run: SQLX_OFFLINE=true cargo build --verbose
    - name: Run tests
      run: SQLX_OFFLINE=true cargo test --verbose
