name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Fmt
      run: cargo fmt
    - name: Clippy
      run: cargo clippy --all-features
    - name: Run tests
      run: cargo test --all-features --verbose
    - name: Build
      run: cargo build --all-features --verbose
